### ISSUE TITLE
Make use of lombok on POJO containers instead of setter and getters.

### ISSUE THREAD

**Issue by jmcloud20** [kristan-dev/upskilling#4]

**Comment by kristan-dev** [comment]
Implemented Lombok by adding lombok to my dependencies and removing my getters and setters from my model.
As part of implementing lombok, the model now has the following annotations to auto create the getters and setters; @Getter @Setter @NoArgsConstructor.

For POJO containers, I could not find an exact reference for a "POJO Container" but have implemented my classes to be POJOs based on the rules set by the reference here: https://www.geeksforgeeks.org/pojo-vs-java-beans

RestService.java no longer implements an interface and instead specifies the Path and other properties in itself.

**Comment by jmcloud20** [comment]
You may use, @Data, @NoArgsConstructor, @AllArgsConstructor, @Builder. If using intellij, have annotation processing available.
@Getter / @Setter for selective use, @Slf4j for logging.

**Comment by kristan-dev** [comment]
Thanks, will consider this part of our growing set of coding standards. Will do a read up on what those other annotations do.

**Comment by kristan-dev** [comment]
Updated kristan-jax-rs project to implement lombok.Data, also added implementation for lombok.Builder but code is commented out to favor the use of @Data, for this use case. A lot of the code on the repository and model was trimmed out because of the implementation of lombok.
