### ISSUE TITLE
Try to use and implement CrudeRepository.

### ISSUE THREAD

**Issue by jmcloud20** [kristan-dev/upskilling#5]

**Comment by kristan-dev** [comment]
Hi @jmcloud20 

I'm assuming that you meant CRUD repository here (https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html). Please advise, if otherwise.

**Comment by jmcloud20** [comment]
Yes, you may check https://github.com/jmcloud20/mssc-beer-service specifically:
* BeerLoader - adding records to the repository during loading.
* Refer to domain and model classes for the usage of the builder pattern on POJO's and DTO's (Data Transfer Objects).

**Comment by kristan-dev** [comment]
Tried to implement repository usinf @builder just as referenced in your github project above.
Also tried to simplify a lot of the classes (for kristan-jax-rs) project to follow POJO patterns.

updates can be seen from latest pull request https://github.com/kristan-dev/upskilling/pull/6
